name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'thank you for noticing and raising an issue with us'
        pr-message: 'I am so excited to have you check my code. By the way, you can always drop me a message @d_k_rathod on twitter or drop me an hello at rathoddharmendra.business@gmail.com'

    - name: Send email
      uses: dawidd6/action-send-mail@v3.5.0
      
    - name: Send some mail
      uses: wadeww/send-email-action@master
      with:
        server_address: smtp.gmail.com
        port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Workflow finished
        body: Job completed ${{job.status}}
        to: john@denver.com, elton@john.com
        from: Me
